language: php

php:
    - 5.5
    - 7.0

before_script:
    - composer install --dev --prefer-source

script: phpunit --coverage-clover build/logs/clover.xml

notifications:
    email: false

after_script:
    - php vendor/bin/coveralls -v
